
package holiday.web.wsdl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b14002
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HolidaysSOAP", targetNamespace = "http://soapwebservice.worldholidaysandevents.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HolidaysSOAP {


    /**
     * 
     * @param country
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getStateListWrapper", targetNamespace = "http://soapwebservice.worldholidaysandevents.com/", className = "holiday.web.wsdl.GetStateListWrapper")
    @ResponseWrapper(localName = "getStateListWrapperResponse", targetNamespace = "http://soapwebservice.worldholidaysandevents.com/", className = "holiday.web.wsdl.GetStateListWrapperResponse")
    @Action(input = "http://soapwebservice.worldholidaysandevents.com/HolidaysSOAP/getStateListWrapperRequest", output = "http://soapwebservice.worldholidaysandevents.com/HolidaysSOAP/getStateListWrapperResponse")
    public String getStateListWrapper(
        @WebParam(name = "country", targetNamespace = "")
        String country);

    /**
     * 
     * @param country
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCountryCityListWrapper", targetNamespace = "http://soapwebservice.worldholidaysandevents.com/", className = "holiday.web.wsdl.GetCountryCityListWrapper")
    @ResponseWrapper(localName = "getCountryCityListWrapperResponse", targetNamespace = "http://soapwebservice.worldholidaysandevents.com/", className = "holiday.web.wsdl.GetCountryCityListWrapperResponse")
    @Action(input = "http://soapwebservice.worldholidaysandevents.com/HolidaysSOAP/getCountryCityListWrapperRequest", output = "http://soapwebservice.worldholidaysandevents.com/HolidaysSOAP/getCountryCityListWrapperResponse")
    public String getCountryCityListWrapper(
        @WebParam(name = "country", targetNamespace = "")
        String country);

    /**
     * 
     * @param country
     * @param state
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getStateCityListWrapper", targetNamespace = "http://soapwebservice.worldholidaysandevents.com/", className = "holiday.web.wsdl.GetStateCityListWrapper")
    @ResponseWrapper(localName = "getStateCityListWrapperResponse", targetNamespace = "http://soapwebservice.worldholidaysandevents.com/", className = "holiday.web.wsdl.GetStateCityListWrapperResponse")
    @Action(input = "http://soapwebservice.worldholidaysandevents.com/HolidaysSOAP/getStateCityListWrapperRequest", output = "http://soapwebservice.worldholidaysandevents.com/HolidaysSOAP/getStateCityListWrapperResponse")
    public String getStateCityListWrapper(
        @WebParam(name = "country", targetNamespace = "")
        String country,
        @WebParam(name = "state", targetNamespace = "")
        String state);

    /**
     * 
     * @param fromDay
     * @param throughYear
     * @param country
     * @param city
     * @param year
     * @param fromYear
     * @param throughday
     * @param throughMonth
     * @param fromMonth
     * @param state
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getHolidayBeanListWrapper", targetNamespace = "http://soapwebservice.worldholidaysandevents.com/", className = "holiday.web.wsdl.GetHolidayBeanListWrapper")
    @ResponseWrapper(localName = "getHolidayBeanListWrapperResponse", targetNamespace = "http://soapwebservice.worldholidaysandevents.com/", className = "holiday.web.wsdl.GetHolidayBeanListWrapperResponse")
    @Action(input = "http://soapwebservice.worldholidaysandevents.com/HolidaysSOAP/getHolidayBeanListWrapperRequest", output = "http://soapwebservice.worldholidaysandevents.com/HolidaysSOAP/getHolidayBeanListWrapperResponse")
    public String getHolidayBeanListWrapper(
        @WebParam(name = "country", targetNamespace = "")
        String country,
        @WebParam(name = "state", targetNamespace = "")
        String state,
        @WebParam(name = "city", targetNamespace = "")
        String city,
        @WebParam(name = "year", targetNamespace = "")
        String year,
        @WebParam(name = "fromMonth", targetNamespace = "")
        String fromMonth,
        @WebParam(name = "fromDay", targetNamespace = "")
        String fromDay,
        @WebParam(name = "fromYear", targetNamespace = "")
        String fromYear,
        @WebParam(name = "throughMonth", targetNamespace = "")
        String throughMonth,
        @WebParam(name = "throughday", targetNamespace = "")
        String throughday,
        @WebParam(name = "throughYear", targetNamespace = "")
        String throughYear);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCountryListWrapper", targetNamespace = "http://soapwebservice.worldholidaysandevents.com/", className = "holiday.web.wsdl.GetCountryListWrapper")
    @ResponseWrapper(localName = "getCountryListWrapperResponse", targetNamespace = "http://soapwebservice.worldholidaysandevents.com/", className = "holiday.web.wsdl.GetCountryListWrapperResponse")
    @Action(input = "http://soapwebservice.worldholidaysandevents.com/HolidaysSOAP/getCountryListWrapperRequest", output = "http://soapwebservice.worldholidaysandevents.com/HolidaysSOAP/getCountryListWrapperResponse")
    public String getCountryListWrapper();

}
