
package holiday.web.wsdl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b14002
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "HolidaysSOAPService", targetNamespace = "http://soapwebservice.worldholidaysandevents.com/", wsdlLocation = "http://www.worldholidaysandevents.com/HolidaysSOAP/HolidaysSOAPService?WSDL")
public class HolidaysSOAPService
    extends Service
{

    private final static URL HOLIDAYSSOAPSERVICE_WSDL_LOCATION;
    private final static WebServiceException HOLIDAYSSOAPSERVICE_EXCEPTION;
    private final static QName HOLIDAYSSOAPSERVICE_QNAME = new QName("http://soapwebservice.worldholidaysandevents.com/", "HolidaysSOAPService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://www.worldholidaysandevents.com/HolidaysSOAP/HolidaysSOAPService?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        HOLIDAYSSOAPSERVICE_WSDL_LOCATION = url;
        HOLIDAYSSOAPSERVICE_EXCEPTION = e;
    }

    public HolidaysSOAPService() {
        super(__getWsdlLocation(), HOLIDAYSSOAPSERVICE_QNAME);
    }

    public HolidaysSOAPService(WebServiceFeature... features) {
        super(__getWsdlLocation(), HOLIDAYSSOAPSERVICE_QNAME, features);
    }

    public HolidaysSOAPService(URL wsdlLocation) {
        super(wsdlLocation, HOLIDAYSSOAPSERVICE_QNAME);
    }

    public HolidaysSOAPService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, HOLIDAYSSOAPSERVICE_QNAME, features);
    }

    public HolidaysSOAPService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HolidaysSOAPService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns HolidaysSOAP
     */
    @WebEndpoint(name = "HolidaysSOAPPort")
    public HolidaysSOAP getHolidaysSOAPPort() {
        return super.getPort(new QName("http://soapwebservice.worldholidaysandevents.com/", "HolidaysSOAPPort"), HolidaysSOAP.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HolidaysSOAP
     */
    @WebEndpoint(name = "HolidaysSOAPPort")
    public HolidaysSOAP getHolidaysSOAPPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://soapwebservice.worldholidaysandevents.com/", "HolidaysSOAPPort"), HolidaysSOAP.class, features);
    }

    private static URL __getWsdlLocation() {
        if (HOLIDAYSSOAPSERVICE_EXCEPTION!= null) {
            throw HOLIDAYSSOAPSERVICE_EXCEPTION;
        }
        return HOLIDAYSSOAPSERVICE_WSDL_LOCATION;
    }

}
